# .github/workflows/static.yml

name: Deploy static content to Pages



on:

  push:

    branches: ["main"] # Or your default branch name



  workflow_dispatch:



permissions:

  contents: read

  pages: write

  id-token: write



concurrency:

  group: "pages"

  cancel-in-progress: false



jobs:

  deploy:

    environment:

      name: github-pages

      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:

      - name: Checkout

        uses: actions/checkout@v4



      # --- START: ADD THESE STEPS FOR REACT/VUE/VITE PROJECTS ---

      - name: Setup Node.js

        uses: actions/setup-node@v4

        with:

          node-version: 20 # <--- IMPORTANT: Use the Node.js version your project requires (e.g., 18, 16). Check your package.json 'engines' or project docs.

          cache: 'npm' # Or 'yarn', 'pnpm' if you use those package managers



      - name: Install dependencies

        run: npm install # Or 'yarn install' or 'pnpm install'



      - name: Build project

        run: npm run build # This command creates the 'build/' folder for Create React App

      # --- END: ADD THESE STEPS FOR REACT/VUE/VITE PROJECTS ---



      - name: Upload artifact

        uses: actions/upload-pages-artifact@v3

        with:

          # This path MUST point to the folder containing your final, compiled index.html

          # For Create React App, 'npm run build' outputs to the 'build' directory.

          path: ./build # <--- CRITICAL CHANGE: This needs to be './build'

                        #      (or './dist' if your project outputs to 'dist')



      - name: Deploy to GitHub Pages

        id: deployment

        uses: actions/deploy-pages@v4

    ```



---

